### ISSUE TITLE
Polishing up home page

### ISSUE THREAD

**Issue by mike787k** [csci-499-sp23/team-5-sp23#111]

**Comment by La-Nique** [comment]
created new graphics for site: created new logo, favicon has been updated throughout the site. updated the colors, these will now be used on the site. updated the metadata "insert app name" which is tbd. made new logo/favicon static in top left. links to homepage.
Merge pull request https://github.com/csci-499-sp23/team-5-sp23/pull/129 from csci-499-sp23/styling

**Comment by La-Nique** [comment]
fixed linkage inspect errors by removing code from index.html and replacing it with code from previous project. restyling entire site. homepage is now stylized to match new APIs. moved "global" css to global css file; makes easier to look through everything so nothing gets overridden since all css is global.

Merge pull request https://github.com/csci-499-sp23/team-5-sp23/pull/127 from csci-499-sp23/styling
